# This is a GitHub Actions workflow configuration file for Continuous Integration (CI).
name: CI workflow

on:
  # Trigger the workflow on push events to the main branch.
  push:
    branches: ["main"]
  # Trigger the workflow on pull request events targeting the main branch.
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Use the latest Ubuntu environment for the job.
    runs-on: ubuntu-latest
    # Use a Python 3.9 slim container for the job.
    container: python:3.9-slim
    steps:
        # 'Checkout' step
      - name: Checkout
        # use the action actions/checkout@v3 to checkout the code from the repository
        uses: actions/checkout@v3
        # 'Install dependencies' step
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        # 'Lint with flake8' step 
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
        # 'Run unit tests with nose' step
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app